In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
x = np.array([
    [1, 1, 1],
    [1, 1, -1],
    [1, -1, 1],
    [1, -1, -1],
    [-1, 1, 1],
    [-1, 1, -1],
    [-1, -1, 1],
    [-1, -1, -1]
])

x_t = x.T

y = np.array([-1, 1, 1, 1, -1, 1, 1, -1])

print(x_t.shape, x.shape)

(3, 8) (8, 3)


In [3]:
def linear_regression(x, y):
    x = np.hstack((x, np.ones((x.shape[0], 1))))
    w = np.dot(la.pinv(x), y)
    return x, w

In [4]:
extended_x, w = linear_regression(x,y) 
y_hat = np.dot(extended_x, w)
print(y_hat)
print(y_hat - y)

[-3.88578059e-16  5.00000000e-01  5.00000000e-01  1.00000000e+00
 -5.00000000e-01 -5.55111512e-17 -1.66533454e-16  5.00000000e-01]
[ 1.  -0.5 -0.5  0.   0.5 -1.  -1.   1.5]


### Parity function

In [5]:
from itertools import permutations, combinations
from operator import itemgetter 

In [6]:
def parity_function(x):
    power_set = []
    indexes = np.arange(len(x))

    for i in range(len(x)):
        power_set.append(combinations(indexes, i+1))

    output = [1]

    for power in power_set:
        for index in power:
            index = list(index)
            items = itemgetter(*index)(x)
            if len(index) > 1:
                output.append(np.prod(list(items)))
            else:
                output.append(items)

    return output

In [7]:
print(parity_function([2,3,4]))

[1, 2, 3, 4, 6, 8, 12, 24]


In [8]:
features = []
for row in x:
    features.append(parity_function(row))

extended_x, w = linear_regression(np.array(features),y) 
y_hat = np.dot(extended_x, w)
print(y_hat)
print(y)

[-1.  1.  1.  1. -1.  1.  1. -1.]
[-1  1  1  1 -1  1  1 -1]
